# install with conda env create -f mds574.yaml

name: amazon-prime
channels:
  - conda-forge
  - defaults
dependencies:
  - python>= 3.11
  - altair-all= 5.4.*
  - pandas>= 2.2
  - matplotlib>= 3.10 

