# install with conda env create -f environment.yaml

name: amazon-prime
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  
  - altair=5.4.*
  - pandas>=2.2
  - matplotlib>=3.10
  - dash=2.16.1
  - dash-bootstrap-components=1.5.0
  - dash-table
  - pip
  - pip:
      - dash-vega-components
  

